// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type DoneTodo struct {
	ID   string `json:"id"`
	Done bool   `json:"done"`
}

type NewTodo struct {
	Text   string `json:"text"`
	UserID string `json:"userId"`
}
